version: 3

pullapprove_conditions:
- "'WIP' not in title"

roups:
  code:
    reviewers:
      users:
      - ValManP
    reviews:
      required: 2  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
